// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	context "context"

	maps "googlemaps.github.io/maps"

	mock "github.com/stretchr/testify/mock"
)

// GoogleAPIClient is an autogenerated mock type for the GoogleAPIClient type
type GoogleAPIClient struct {
	mock.Mock
}

// Geocode provides a mock function with given fields: ctx, r
func (_m *GoogleAPIClient) Geocode(ctx context.Context, r *maps.GeocodingRequest) ([]maps.GeocodingResult, error) {
	ret := _m.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for Geocode")
	}

	var r0 []maps.GeocodingResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *maps.GeocodingRequest) ([]maps.GeocodingResult, error)); ok {
		return rf(ctx, r)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *maps.GeocodingRequest) []maps.GeocodingResult); ok {
		r0 = rf(ctx, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]maps.GeocodingResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *maps.GeocodingRequest) error); ok {
		r1 = rf(ctx, r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGoogleAPIClient creates a new instance of GoogleAPIClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGoogleAPIClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *GoogleAPIClient {
	mock := &GoogleAPIClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
