// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/Houeta/geocoding-service/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// Interface is an autogenerated mock type for the Interface type
type Interface struct {
	mock.Mock
}

// FetchTasksForGeocoding provides a mock function with given fields: ctx, limit
func (_m *Interface) FetchTasksForGeocoding(ctx context.Context, limit int) ([]models.Task, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for FetchTasksForGeocoding")
	}

	var r0 []models.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]models.Task, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []models.Task); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IncrementFailureCount provides a mock function with given fields: ctx, taskID, errMsg
func (_m *Interface) IncrementFailureCount(ctx context.Context, taskID int, errMsg string) error {
	ret := _m.Called(ctx, taskID, errMsg)

	if len(ret) == 0 {
		panic("no return value specified for IncrementFailureCount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string) error); ok {
		r0 = rf(ctx, taskID, errMsg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateTaskCoordinates provides a mock function with given fields: ctx, taskID, coords
func (_m *Interface) UpdateTaskCoordinates(ctx context.Context, taskID int, coords models.Coordinates) error {
	ret := _m.Called(ctx, taskID, coords)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTaskCoordinates")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, models.Coordinates) error); ok {
		r0 = rf(ctx, taskID, coords)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewInterface creates a new instance of Interface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *Interface {
	mock := &Interface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
